patrolling_node:
  ros__parameters:
    use_sim_time: true
    frame_id: map
    waypoints: [wp1, wp2, wp3, wp4, wp5]
    wp1: [4.23, -3.0, 0.0]
    wp2: [-1.47, -4.08, 1.57]
    wp3: [-6.76, -3.01, 3.14]
    wp4: [-7.36, -0.38, 0.0]
    wp5: [0.0, 0.5, 0.0]
